# Copyright (c) 2024-2025 Joel Torres
# Distributed under the MIT License. See the accompanying file LICENSE.

services:
  bitcoin_exporter:
    build: .
    volumes:
      - type: bind
        source: ./exporter.yaml
        target: /opt/.btcore/exporter.yaml
    ports:
      - "8000:8000"
    restart: always
