{
 "title": "Bitcoin Core",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_network_info_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_blockchain_info_blocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_net_totals_total_bytes_sent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_net_totals_total_bytes_recv",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "bitcoin_network_info_connections_in",
     "legendFormat": "connections_in"
    },
    {
     "expr": "bitcoin_network_info_connections_out",
     "legendFormat": "connections_out"
    },
    {
     "expr": "bitcoin_network_info_connections",
     "legendFormat": "connections_total"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bitcoin_net_totals_total_bytes_sent",
     "legendFormat": "sent"
    },
    {
     "expr": "bitcoin_net_totals_total_bytes_recv",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Mempool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bitcoin_mem_pool_info_usage", "legendFormat": "usage" }
   ]
  },
  {
   "title": "Mempool  TX Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "bitcoin_mem_pool_info_size", "legendFormat": "count" }
   ]
  },
  {
   "title": "Size on disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bitcoin_blockchain_info_size_on_disk",
     "legendFormat": "size_on_disk"
    }
   ]
  },
  {
   "title": "Blockchain Verification Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bitcoin_blockchain_info_verification_progress",
     "legendFormat": "verificaion_progress"
    }
   ]
  },
  {
   "title": "Daemon Locked Memory Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bitcoin_memory_info_used", "legendFormat": "used" },
    { "expr": "bitcoin_memory_info_free", "legendFormat": "free" },
    { "expr": "bitcoin_memory_info_total", "legendFormat": "total" }
   ]
  }
 ]
}